# Generated by Django 4.1.7 on 2023-03-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_storefront_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='duration_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='address_CEP',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='address_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='facebook',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='instagram',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='theme',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='youtube',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
