# Generated by Django 4.1.7 on 2023-03-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_alter_services_duration_time_alter_services_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='store_id',
            new_name='store',
        ),
    ]
