# Generated by Django 4.1.7 on 2023-03-10 14:48

from django.db import migrations, models
import vitrine.models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_rename_store_id_services_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=vitrine.models.upload_to),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vitrine.models.upload_to),
        ),
    ]
