# Generated by Django 4.1.7 on 2023-03-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0005_alter_storefront_background_alter_storefront_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storefront',
            old_name='owner',
            new_name='creator',
        ),
    ]
